In [1]:
import yfinance as yf
from datetime import date

In [2]:
watch_list=["AAPL", "NVDA", "GLD", "TSLA", "GOOG"]

In [3]:
# tickers = yf.Tickers(watch_list)
# tickers.tickers['AAPL'].info
data = yf.download(watch_list, period='3mo')

C:\Users\a7don\AppData\Local\Temp\ipykernel_14116\3115269954.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(watch_list, period='3mo')
[*********************100%***********************]  5 of 5 completed

In [4]:
dt = date(2025, 4, 22)

d = dt.strftime("%Y%m%d")
data.Open.AAPL[d].round(2)

195.86

In [10]:
data

Price            Close                                                  \
Ticker            AAPL         GLD        GOOG        NVDA        TSLA
Date
2025-04-21  192.907028  315.589996  149.680084   96.903275  227.500000
2025-04-22  199.478424  311.109985  153.715225   98.883133  237.970001
2025-04-23  204.332062  303.649994  157.530655  102.702866  250.740005
2025-04-24  208.097107  308.070007  161.276154  106.422607  259.510010
2025-04-25  209.005920  304.730011  163.653290  111.002296  284.950012
...                ...         ...         ...         ...         ...
2025-07-14  208.619995  308.010010  182.809998  164.070007  316.899994
2025-07-15  209.110001  306.730011  183.100006  170.699997  310.779999
2025-07-16  210.160004  308.260010  183.770004  171.369995  321.670013
2025-07-17  210.020004  307.589996  184.699997  173.000000  319.410004
2025-07-18  211.179993  308.390015  185.940002  172.410004  329.649994

Price             High                                                  ...  \
Ticker            AAPL         GLD        GOOG        NVDA        TSLA  ...
Date                                                                    ...
2025-04-21  193.546189  316.410004  150.878641   99.433098  232.210007  ...
2025-04-22  201.325992  317.630005  154.424380   99.803067  242.789993  ...
2025-04-23  207.727603  304.739990  159.827897  104.792724  259.450012  ...
2025-04-24  208.556511  308.500000  161.515871  106.532600  259.540009  ...
2025-04-25  209.475306  305.369995  168.038019  111.912229  286.850006  ...
...                ...         ...         ...         ...         ...  ...
2025-07-14  210.910004  309.380005  184.729996  165.490005  322.600006  ...
2025-07-15  211.889999  308.739990  185.410004  172.399994  321.200012  ...
2025-07-16  212.399994  311.089996  185.335007  171.750000  323.500000  ...
2025-07-17  211.800003  307.670013  185.186996  174.160004  324.339996  ...
2025-07-18  211.789993  309.369995  187.360001  174.240005  330.899994  ...

Price             Open                                                  \
Ticker            AAPL         GLD        GOOG        NVDA        TSLA
Date
2025-04-21  193.016885  315.019989  150.783753   98.763138  230.259995
2025-04-22  195.863154  317.489990  150.888636   98.773140  230.960007
2025-04-23  205.730222  304.179993  157.720429  104.512737  254.860001
2025-04-24  204.621669  306.980011  158.334682  103.472815  250.500000
2025-04-25  206.099728  301.779999  166.899388  106.842582  261.690002
...                ...         ...         ...         ...         ...
2025-07-14  209.929993  309.070007  182.070007  165.369995  317.730011
2025-07-15  209.220001  307.730011  183.940002  171.190002  319.679993
2025-07-16  210.300003  307.109985  184.320007  171.059998  312.799988
2025-07-17  210.570007  305.500000  183.115005  172.020004  323.149994
2025-07-18  210.755005  309.239990  186.649994  173.729996  322.000000

Price         Volume
Ticker          AAPL       GLD      GOOG       NVDA       TSLA
Date
2025-04-21  46742500  20372300  16147800  288501100   97768000
2025-04-22  52976400  35242300  15910300  241004800  120858500
2025-04-23  52929200  25421500  18575700  247526000  150381900
2025-04-24  47311000  10845000  30787500  220815000   94464200
2025-04-25  38222300  10691600  35148100  251064700  167560700
...              ...       ...       ...        ...        ...
2025-07-14  38840100   5772900  20990400  136975800   78043400
2025-07-15  42296300   8149000  23911600  230627400   77556300
2025-07-16  47490500  17693100  21152600  158831500   97284800
2025-07-17  48068100   6642300  21654400  160841100   73922900
2025-07-18  48317144   5437996  20889360  145456141   93624355

[62 rows x 25 columns]

In [5]:
day_idx = data.index.get_loc(d)

In [6]:
next_day_idx = day_idx + 1
next_d = data.Open.AAPL.index[next_day_idx]
next_d

Timestamp('2025-04-23 00:00:00')

In [7]:
data.Open.AAPL[next_d].round(2)

205.73

In [9]:
data.Open["AAPL"][next_d]

205.7302222309065